name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  black:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Run black
      run: |
        black --check --diff .

  isort:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Run isort
      run: |
        isort --check-only --diff .

  mypy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Run mypy
      run: |
        mypy --pretty --strict .

  pylint:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py')
